Repository basbruss/adaptive-cover, pull requests merged in 2024-03, with the labels that each got.

#45 Update config flow
  custom_components/adaptive_cover/calculation.py
  custom_components/adaptive_cover/config_flow.py
  custom_components/adaptive_cover/const.py
  custom_components/adaptive_cover/sensor.py
  custom_components/adaptive_cover/strings.json
  custom_components/adaptive_cover/translations/en.json
  custom_components/adaptive_cover/translations/nl.json
Labels: 🚀 enhancement

#54 Add climate mode switch
  custom_components/adaptive_cover/config_flow.py
  custom_components/adaptive_cover/coordinator.py
  custom_components/adaptive_cover/sensor.py
  custom_components/adaptive_cover/strings.json
  custom_components/adaptive_cover/translations/en.json
  custom_components/adaptive_cover/translations/nl.json
Labels: ✨ new-feature

#55 Add binary_sensor platform
  custom_components/adaptive_cover/__init__.py
  custom_components/adaptive_cover/binary_sensor.py
  custom_components/adaptive_cover/coordinator.py
  custom_components/adaptive_cover/icons.json
Labels: ✨ new-feature

#56 Add additional sensors
  custom_components/adaptive_cover/calculation.py
  custom_components/adaptive_cover/coordinator.py
  custom_components/adaptive_cover/icons.json
  custom_components/adaptive_cover/sensor.py
Labels: ✨ new-feature

#65 Fix states not updating
  custom_components/adaptive_cover/calculation.py
  custom_components/adaptive_cover/config_flow.py
  custom_components/adaptive_cover/sensor.py
Labels: 🐛 bugfix

#66 Fix climate state is not numeric
  custom_components/adaptive_cover/calculation.py
Labels: 🐛 bugfix

#67 Add extra update calls
  custom_components/adaptive_cover/sensor.py
Labels: python

#71 Fix config flow
  custom_components/adaptive_cover/config_flow.py
  custom_components/adaptive_cover/translations/nl.json
Labels: 🐛 bugfix

#72 Fix Config entry was never loaded
  custom_components/adaptive_cover/__init__.py
  custom_components/adaptive_cover/switch.py
Labels: 🐛 bugfix

#78 Add helper to get safe attributes
  custom_components/adaptive_cover/calculation.py
  custom_components/adaptive_cover/coordinator.py
  custom_components/adaptive_cover/helpers.py
Labels: python

#77 Update weather logic
  custom_components/adaptive_cover/calculation.py
Labels: 🚀 enhancement

#76 Fix blueprint not added
  custom_components/adaptive_cover/__init__.py
Labels: 🐛 bugfix, blueprint

#79 Add outdoor temperature control
  custom_components/adaptive_cover/calculation.py
  custom_components/adaptive_cover/config_flow.py
  custom_components/adaptive_cover/const.py
  custom_components/adaptive_cover/coordinator.py
  custom_components/adaptive_cover/helpers.py
  custom_components/adaptive_cover/sensor.py
  custom_components/adaptive_cover/strings.json
  custom_components/adaptive_cover/switch.py
  custom_components/adaptive_cover/translations/en.json
  custom_components/adaptive_cover/translations/nl.json
Labels: ✨ new-feature

#80 Fix bug get_safe_state
  custom_components/adaptive_cover/calculation.py
  custom_components/adaptive_cover/coordinator.py
  custom_components/adaptive_cover/helpers.py
Labels: 🐛 bugfix

#84 Account for sunrise when determining sunset_valid
  custom_components/adaptive_cover/calculation.py
  custom_components/adaptive_cover/sun.py
Labels: 🚀 enhancement
