Repository basbruss/adaptive-cover, pull requests merged in 2024-06, with the labels that each got.

#192 Minor Documentation improvements
  README.md
Labels: 📚 documentation

#197 Add manual override sensitivity options
  custom_components/adaptive_cover/config_flow.py
  custom_components/adaptive_cover/const.py
  custom_components/adaptive_cover/coordinator.py
  custom_components/adaptive_cover/strings.json
  custom_components/adaptive_cover/translations/en.json
  custom_components/adaptive_cover/translations/nl.json
Labels: 🚀 enhancement

#196 Fix endtime when `00:00:00`
  custom_components/adaptive_cover/coordinator.py
Labels: 🐛 bugfix

#199 Remove old horizontal artifacts from config flow
  custom_components/adaptive_cover/config_flow.py
  custom_components/adaptive_cover/strings.json
  custom_components/adaptive_cover/translations/en.json
  custom_components/adaptive_cover/translations/nl.json
Labels: python, configuration

#200 Reduce calculation operation
  custom_components/adaptive_cover/coordinator.py
  custom_components/adaptive_cover/switch.py
Labels: python

#205 Add diagnostics
  custom_components/adaptive_cover/diagnostics.py
Labels: 🚀 enhancement

#204 Always return to default options
  custom_components/adaptive_cover/coordinator.py
Labels: 🐛 bugfix

#211 Apply always inverse state if selected
  custom_components/adaptive_cover/coordinator.py
Labels: 🐛 bugfix

#206 Add Lux and Irradiance support to climate mode
  .devcontainer/devcontainer.json
  .pre-commit-config.yaml
  README.md
  config/configuration.yaml
  custom_components/adaptive_cover/calculation.py
  custom_components/adaptive_cover/config_flow.py
  custom_components/adaptive_cover/const.py
  custom_components/adaptive_cover/coordinator.py
  custom_components/adaptive_cover/icons.json
  custom_components/adaptive_cover/strings.json
  custom_components/adaptive_cover/switch.py
  custom_components/adaptive_cover/translations/en.json
  custom_components/adaptive_cover/translations/nl.json
Labels: ✨ new-feature

#201 Fix Import module
  custom_components/adaptive_cover/coordinator.py
Labels: 🐛 bugfix

#212 Interpolation shutters
  custom_components/adaptive_cover/config_flow.py
  custom_components/adaptive_cover/const.py
  custom_components/adaptive_cover/coordinator.py
  custom_components/adaptive_cover/strings.json
  custom_components/adaptive_cover/translations/en.json
  custom_components/adaptive_cover/translations/nl.json
Labels: 🚀 enhancement

#216 Fix always inverse state
  custom_components/adaptive_cover/coordinator.py
Labels: 🐛 bugfix

#215 Fix link anchor in README.md
  README.md
Labels: 📚 documentation

#220 Add state to button call
  custom_components/adaptive_cover/button.py
Labels: 🐛 bugfix

#221 Fix datetime comparison
  custom_components/adaptive_cover/coordinator.py
Labels: 🐛 bugfix

#224 Fix lux/irradiance comparison
  custom_components/adaptive_cover/calculation.py
Labels: 🐛 bugfix

#227 fix interpolation not configurable due to missing new range
  custom_components/adaptive_cover/config_flow.py
  custom_components/adaptive_cover/coordinator.py
Labels: 🐛 bugfix
