Repository basbruss/adaptive-cover, pull requests merged in 2024-05, with the labels that each got.

#132 Check reset for all events
  custom_components/adaptive_cover/coordinator.py
Labels: 🐛 bugfix

#128 Update async event state change
  custom_components/adaptive_cover/__init__.py
  custom_components/adaptive_cover/coordinator.py
  hacs.json
Labels: 🐛 bugfix

#133 Update docs with variables
  README.md
  images/image-1.png
  images/image-2.png
  images/image.png
Labels: 📚 documentation

#153 Fix `input_datetime` helper error
  custom_components/adaptive_cover/config_flow.py
  custom_components/adaptive_cover/coordinator.py
  custom_components/adaptive_cover/helpers.py
  custom_components/adaptive_cover/switch.py
Labels: 🐛 bugfix

#152 Add end time variables
  README.md
  custom_components/adaptive_cover/config_flow.py
  custom_components/adaptive_cover/const.py
  custom_components/adaptive_cover/coordinator.py
  custom_components/adaptive_cover/strings.json
  custom_components/adaptive_cover/translations/en.json
  custom_components/adaptive_cover/translations/nl.json
Labels: 🚀 enhancement

#162 Add blind spot including elevation
  custom_components/adaptive_cover/calculation.py
  custom_components/adaptive_cover/config_flow.py
  custom_components/adaptive_cover/const.py
  custom_components/adaptive_cover/coordinator.py
  custom_components/adaptive_cover/strings.json
  custom_components/adaptive_cover/translations/en.json
  custom_components/adaptive_cover/translations/nl.json
Labels: ✨ new-feature

#164 Add min/max Elevation controls
  custom_components/adaptive_cover/calculation.py
  custom_components/adaptive_cover/config_flow.py
  custom_components/adaptive_cover/const.py
  custom_components/adaptive_cover/coordinator.py
  custom_components/adaptive_cover/strings.json
  custom_components/adaptive_cover/translations/en.json
  custom_components/adaptive_cover/translations/nl.json
Labels: ✨ new-feature

#168 add transparent blind option to climate mode
  custom_components/adaptive_cover/calculation.py
  custom_components/adaptive_cover/config_flow.py
  custom_components/adaptive_cover/const.py
  custom_components/adaptive_cover/coordinator.py
  custom_components/adaptive_cover/translations/en.json
Labels: ✨ new-feature

#169 Prioritize outside temperature sensor over weather entity
  custom_components/adaptive_cover/calculation.py
Labels: 🚀 enhancement

#170 Update debug logging
  custom_components/adaptive_cover/coordinator.py
Labels: 🚀 enhancement, python

#177 Fix test in Config Flow
  custom_components/adaptive_cover/config_flow.py
Labels: 🐛 bugfix

#173 build(requirements.txt): separate development dependencies
  requirements-dev.txt
  requirements.txt
  scripts/setup
Labels: dependencies, dev-container

#174 Feat: update notebook
  custom_components/adaptive_cover/calculation.py
  custom_components/adaptive_cover/sun.py
  custom_components/adaptive_cover/test_env.ipynb
  notebooks/test_env.ipynb
Labels: python

#183 Update __init__.py
  custom_components/adaptive_cover/__init__.py
Labels: 🐛 bugfix

#189 Fix not updating at end time
  custom_components/adaptive_cover/coordinator.py
Labels: 🐛 bugfix
